# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='обо мне'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles//%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
