# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180613_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
