# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180620_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
    ]
