# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
